resolver: lts-6.6
packages:
- '.'
- location:
    git:  https://github.com/transient-haskell/transient.git
    commit: b15972a71634efe3b85a1480cecc35b50d424e5d

  extra-dep: true
extra-package-dbs: []
flags: {}

